### ISSUE TITLE
discount_memory (multiplicative)

### ISSUE THREAD

**Issue by cvanbommel** [benjaminbenteke/EWO_Methods#1]
In the line "factor= discount_factor**(k-i)" what is i?

**Comment by benjaminbenteke** [comment]
all weeks before week k.

**Comment by cvanbommel** [comment]
I'll be more specific, "i" does not appear to be defined within the function, so what is its purpose?

**Comment by benjaminbenteke** [comment]
I  can see it. I should have another for loop i= 1:k. 
<img width="536" alt="Screenshot 2024-05-10 at 02 03 14" src="https://github.com/benjaminbenteke/EWO_Methods/assets/57951412/c7a914fd-4aa8-40b1-ac70-9242d73bec42">

I've fixed it.
