### ISSUE TITLE
horizon (multiplicative)

### ISSUE THREAD

**Issue by cvanbommel** [benjaminbenteke/EWO_Methods#2]
It appears that the data is being corrected based on all previous forecasts, but at longer horizons, this doesn't make sense, as the truth data for the most recent forecasts is not available.

**Comment by benjaminbenteke** [comment]
I think, all truth data for weeks in the expanding window are available for each horizon. We use them to blend forecast for short and longer horizons. I believe the learning and correction made on existing weeks (forecast and truth data are available). Otherwise,  even the optimization will not be done since we'll miss truth data.

**Comment by benjaminbenteke** [comment]
Thank you!

**Comment by cvanbommel** [comment]
The optimization runs using

past_weeks= all_dates[:n_past_weeks-1]
week_to_forecast= all_dates[n_past_weeks+h]
validate_Week= all_dates[n_past_weeks-1]

but I'm not seeing a similar adjustment when discount_memory is called, it appears to me to be using all data.

**Comment by benjaminbenteke** [comment]
It can't be seen in the main function. However,  the selected_weeks function is our helper function that spits data into train validation weeks. 

def selected_weeks(i, csv_files, number_wk_ahead= int(target[0])):
    past_weeks= all_dates[:n_past_weeks-1]
    forecasted_week= all_dates[n_past_weeks+h] #all_dates[n_past_weeks+h-1]
    
    validate_Week= all_dates[:n_past_weeks][-1] #all_dates[n_past_weeks] #past_weeks[-1]
    
    res_future= [csv for csv in csv_files if forecasted_week in csv]
    val_file= [csv for csv in csv_files if validate_Week in csv]
    res_past= []
    for w in past_weeks:
        for week_subs in csv_files:
            if w in week_subs:
                res_past.append(week_subs)
    return res_past, res_future,val_file

**Comment by cvanbommel** [comment]
Ah yes, I see what you mean now, thank you!
