### ISSUE TITLE
Projected Gradient Descent

### ISSUE THREAD

**Issue by cvanbommel** [benjaminbenteke/EWO_Methods#6]
When updating theta in the learning_step, the code adjusts theta by setting negative values to 0 and rescaling to 1.  But this is not a projection to the closest valid set of weights.  Consider the following:

theta = (-0.2, 0.4)

With the code as written, theta is adjusted to (0, 1).  The distance to the calculated value of theta is 0.63.

However, adjusting to the closest point should give (0.2, 0.8).  The distance to the calculated value is 0.57.

Also notice that we encounter an error in the code if we obtain a theta in which all values are negative.

**Comment by benjaminbenteke** [comment]
This makes sense to me. However, the objective value of (0. 2,0. 8) may be > the one for (0,1). If i use:

def objective_function(x):
    return (x[0] - 1)**2 + (x[1] - 2)**2

def gradient_function(x):
    return np.array([2*(x[0] - 1), 2*(x[1] - 2)])

**Comment by cvanbommel** [comment]
That the code provides a better objective value in a single instance does not change the fact that the method cannot be described as projective gradient descent since it does not use projections (and there may be objective functions where the reverse is true).  Is there previous work using this method to adjust the weights after the gradient descent step?

**Comment by benjaminbenteke** [comment]
True. I hope this code solves it properly:


from scipy.optimize import minimize
import numpy as np
def constraint_function(x):
    return np.array([(x[0] + x[1])-1])


def project_into_feasible_set(x,constraint_function):
    result = minimize(lambda x_prime: np.linalg.norm(x_prime - x), x, constraints={'type': 'ineq', 'fun': constraint_function},bounds= [(0,1),(0,1)])
    return result.x

initial_x = np.array([-0.2, 0.4])
project_into_feasible_set(initial_x,constraint_function)

gives: array([0.1996872, 0.8003128])
